# 💙 Support PowerX
#
# PowerX is built to make Windows monitoring, diagnostics,
# optimization, repair, configuration, and software management
# safer, clearer, and more powerful.
#
# Sponsorships help support continued development,
# testing, documentation, infrastructure, and future releases.

github: [Nowalski]
